<?php
/**
 * @file
 * Provides a elasticsearch-based service class for the Search API.
 */

function search_api_elasticsearch_autoload_elastica($class) {
  if (substr($class, 0, 8) === 'Elastica') {
    $file = drupal_get_path('module', 'search_api_elasticsearch') . '/Elastica/lib/' . str_replace('_', '/', $class) . '.php';

    if (file_exists($file)) {
      require_once($file);
    }
  }
}

spl_autoload_register('search_api_elasticsearch_autoload_elastica');

/**
 * Implements hook_search_api_service_info().
 */
function search_api_elasticsearch_search_api_service_info() {
  $services['search_api_elasticsearch_service'] = array(
    'name' => t('Elasticsearch service'),
    'description' => t('
    <p>Index items using a !url_elasticsearch search server.</p>
    <ul>
    <li>All field types are supported.</li>
    <li>Will use internal elasticsearch preprocessors, so Search API preprocessors should for the most part be deactivated.</li>
    <li>See the README.txt file provided with this module for details.</li>
    </ul>',
    array(
      '!url_sphinx' => l(t('Elasticsearch'), 'http://http://www.elasticsearch.org/'),
    )),
    'class' => 'SearchApiElasticsearchService',
  );
  return $services;
}
